### PR TITLE
chore: Update smoldot to the latest version

### LINKED ISSUE #848: update smoldot version to latest

### PR DESCRIPTION
**Pull request by mittal-parth**
Updates smoldot submodule to the latest version using `git submodule update --remote vendor/smoldot`

Closes #848

### CODE REVIEW

**Comment by xlc** [comment]
please also fix CI

**Comment by mittal-parth** [comment]
Hi @xlc 
Two ways to fix the CI here:

1. Update the rust version as the CI is complaining:

```bash
error: package `wasmi_core v0.40.0` cannot be built because it requires rustc 1.80 or newer, while the currently active rustc version is 1.77.2
Either upgrade to rustc 1.80 or newer, or use
cargo update wasmi_core@0.40.0 --precise ver
where `ver` is the latest version of `wasmi_core` supporting rustc 1.77.2
```

2. I did a cargo update in `executor` dir and inside all the `vendor/smoldot/` dirs that had a cargo.toml. This fixes everything but that would make the submodule commit a dirty one.

Which one should we go for?

Thanks!

**Comment by xlc** [comment]
Please update the rust version used in CI
Do `cargo update` in executor if needed. Do not do it inside `vendor/smoldot`.

**Comment by ermalkaleci** [comment]
already bumped

**Pull request closed without merging**
