### PR TITLE
alias state_getStorageAt

### LINKED ISSUE #718: Method not found state_getStorageAt
Hello there, I'm running into this issue when I'm using the latest version of subsquid indexer against Chopsticks v0.9.13
I'm forking Kusama, using this config: https://github.com/ChainSafe/Multix/blob/tbaut-bump-subsquid/chopsticks-config.yml

Here is the error:
```
[00:31:34.428] INFO: Kusama RPC listening on port 8000
    app: "chopsticks"
[00:32:18.199] WARN (rpc): Method not found state_getStorageAt
    app: "chopsticks"
[00:32:18.200] INFO (ws): Error handling request: 'ResponseError: Method not found: state_getStorageAt
    at /home/thib/.npm/_npx/fffae069f13e874a/node_modules/@acala-network/chopsticks/dist/cjs/rpc/index.js:39:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async processRequest (/home/thib/.npm/_npx/fffae069f13e874a/node_modules/@acala-network/chopsticks/dist/cjs/server.js:211:30)
    at async WebSocket.<anonymous> (/home/thib/.npm/_npx/fffae069f13e874a/node_modules/@acala-network/chopsticks/dist/cjs/server.js:273:30)'
```

In case this helps, the trace of the calls with the exact `state_getStorageAt` is the following:
```
00:37:41 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
                                 rpcMethod: state_getStorageAt
                                 rpcParams: ["0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7","0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
00:37:41 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
00:37:41 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
00:37:41 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
00:37:41 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
                                 rpcMethod: state_getStorageAt
                                 rpcParams: ["0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7","0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
                                 rpcResponse: {"id":7,"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found: state_getStorageAt"}}
00:37:41 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0x6b6d12100936161daa7e194db94cd7c24e0d732ce9fcb120a85f117c8ecf2185"]
                                 rpcResponse: {"id":8,"jsonrpc":"2.0","result":{"specName":"kusama","implName":"parity-kusama","authoringVersion":2,"specVersion":1001003,"implVersion":0,"apis":[["0xdf6acb689907609b",4],["0x37e397fc7c91f5e4",2],["0x40fe3ad401f8959a",6],["0xd2bc9897eed08f15",3],["0xf78b278be53f454c",2],["0xaf2c0297a23e6d3d",7],["0x49eaaf1b548a0cb0",3],["0x91d5df18b0d2cf58",2],["0x2a5e924655399e60",1],["0xed99c5acb25eedf5",3],["0xcbca25e39f142387",2],["0x687ad44ad37f03c2",1],["0xab3c0572291feb8b",1],["0xbc9d89904f5b923f",1],["0x37c8bb1350a9a2a8",4],["0xf3ff14d5ab527059",3],["0x17a6bc0d0062aeb3",1],["0x18ef58a3b67ba770",1],["0xfbc577b9d747efd6",1]],"transactionVersion":25,"stateVersion":1}}
00:37:41 FATAL sqd:processor Error: Failed to fetch block 22568473#6b6d1

```

### PR DESCRIPTION
**Pull request by xlc**
closes #718

### CODE REVIEW

**Comment by Tbaut** [comment]
Thanks @xlc this looks like this particular issue is gone.
I did encounter another weird issue though, I let you tell me whether it should be another issue:

```bash
1:11:02 INFO  sqd:processor processing blocks from 22568290
11:11:02 INFO  sqd:processor using chain RPC data source
11:11:02 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 1
                                 rpcMethod: chain_getFinalizedHead
11:11:02 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 1
11:11:02 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 1
                                 rpcMethod: chain_getFinalizedHead
                                 rpcResponse: {"id":1,"jsonrpc":"2.0","result":"0xd1a4a66b79225bfde5c6065fa8932834de607ac040f9a9842e85794129840d5b"}
11:11:02 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 2
                                 rpcMethod: chain_getHeader
                                 rpcParams: ["0xd1a4a66b79225bfde5c6065fa8932834de607ac040f9a9842e85794129840d5b"]
11:11:02 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 2
11:11:02 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 2
                                 rpcMethod: chain_getHeader
                                 rpcParams: ["0xd1a4a66b79225bfde5c6065fa8932834de607ac040f9a9842e85794129840d5b"]
                                 rpcResponse: {"id":2,"jsonrpc":"2.0","result":{"parentHash":"0x88479bb55ea490a0debc42f8220ada66d7724dc9addf76536420daea3e697d7b","number":"0x01585d62","stateRoot":"0xdb73e32e4442a4b1515cb1a76b7c5ec3cdd063a5baa80d2d54e98c1daa757246","extrinsicsRoot":"0xfe59f4a6cc065974bbfd0a7c315b828abce857a19f15cc47357b324b14b2da65","digest":{"logs":["0x0642414245b50101360000001116021100000000903f23074294ead3d63efe78db56412e6a54b3650e3970707a4a2aa243d1310e7194954a52f29b10e4e7c4f9594ef024fbc0a066c46567e9270598e195f6690216397d69fdadc9bdc010b051f2e717e88c99a217ca7fbfe9e3f390675c4ca803","0x04424545468403828dbe644a821f6becbdd74ce17c991fbcc81c351c80c4e5a87b81ab92e2fbad","0x054241424501018c0daaf1ea7ba60c9e6eecb466c0cfba1bffa421dd49f9064671c11538130550994f84ae490473c8d82abab84892331712fa776379d224fc3bfe9e22c3932383"]}}}
11:11:03 INFO  sqd:processor prometheus metrics are served at port 33713
11:11:03 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 3
                                 rpcMethod: chain_getFinalizedHead
11:11:03 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 3
11:11:03 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 3
                                 rpcMethod: chain_getFinalizedHead
                                 rpcResponse: {"id":3,"jsonrpc":"2.0","result":"0xd1a4a66b79225bfde5c6065fa8932834de607ac040f9a9842e85794129840d5b"}
11:11:03 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 4
                                 rpcMethod: chain_getHeader
                                 rpcParams: ["0xd1a4a66b79225bfde5c6065fa8932834de607ac040f9a9842e85794129840d5b"]
11:11:03 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 4
11:11:03 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 4
                                 rpcMethod: chain_getHeader
                                 rpcParams: ["0xd1a4a66b79225bfde5c6065fa8932834de607ac040f9a9842e85794129840d5b"]
                                 rpcResponse: {"id":4,"jsonrpc":"2.0","result":{"parentHash":"0x88479bb55ea490a0debc42f8220ada66d7724dc9addf76536420daea3e697d7b","number":"0x01585d62","stateRoot":"0xdb73e32e4442a4b1515cb1a76b7c5ec3cdd063a5baa80d2d54e98c1daa757246","extrinsicsRoot":"0xfe59f4a6cc065974bbfd0a7c315b828abce857a19f15cc47357b324b14b2da65","digest":{"logs":["0x0642414245b50101360000001116021100000000903f23074294ead3d63efe78db56412e6a54b3650e3970707a4a2aa243d1310e7194954a52f29b10e4e7c4f9594ef024fbc0a066c46567e9270598e195f6690216397d69fdadc9bdc010b051f2e717e88c99a217ca7fbfe9e3f390675c4ca803","0x04424545468403828dbe644a821f6becbdd74ce17c991fbcc81c351c80c4e5a87b81ab92e2fbad","0x054241424501018c0daaf1ea7ba60c9e6eecb466c0cfba1bffa421dd49f9064671c11538130550994f84ae490473c8d82abab84892331712fa776379d224fc3bfe9e22c3932383"]}}}
11:11:03 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 5
                                 rpcMethod: chain_getBlockHash
                                 rpcParams: ["0x1585d62"]
11:11:03 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 5
11:11:03 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 5
                                 rpcMethod: chain_getBlockHash
                                 rpcParams: ["0x1585d62"]
                                 rpcResponse: {"id":5,"jsonrpc":"2.0","result":"0x6e7d988e2b0f4cdafd996913113d63ce3dc371a130ec4ed7d019b61ab64d44c3"}
11:11:03 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 6
                                 rpcMethod: chain_getBlock
                                 rpcParams: ["0x6e7d988e2b0f4cdafd996913113d63ce3dc371a130ec4ed7d019b61ab64d44c3"]
11:11:03 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 6
11:11:05 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 6
                                 rpcMethod: chain_getBlock
                                 rpcParams: ["0x6e7d988e2b0f4cdafd996913113d63ce3dc371a130ec4ed7d019b61ab64d44c3"]
                                 rpcResponse: {"id":6,"jsonrpc":"2.0","result":{"block":{"header":{"parentHash":"0xd44ca70138cb429b522eb8ef8cdd5df613e58402e664466bb1c1573fc92ccdfe","number":"0x015876ca","stateRoot":"0x70223b40f0887dc5773dcd379ce89ce3b081a2dbe2ae757ae0a66e2697260e8b","extrinsicsRoot":"0x1914ad6090be87dffb7ca7fbc97b93991ad8cdcffd41ad1522f61e4d722d2443","digest":{"logs":["0x0642414245b5010177020000862f0211000000006c5eaac36cbfb87de155203b22a8a904c220c2643ee3586da09b326d59e8c702681887e3b6aaa1fb66f1bd5d4108c861947c4b0976ee24e343eb3f2e6fc7bb0192055be7e26cf01d2fdc146330d681c966b019e3063ea19c1d5c313d487fa90f","0x04424545468403bfb9b7690359e8f9b3c5cc7b4abbce3beec8182cc8a8c9e5812b467588c25489","0x0542414245010144edf5269f9235befadf297e84ed0b2fff4e23547f423752659641ea61edf16871617509550ad6080c7b3d7d3027fd611104b5d14bb0d216ff88ea65c267458d"]}},"extrinsics":["0x280402000ba0d439a38e01","0xaafa0100043600a9049101dff0e78e1e27000000000000000 [redacted] bb520cf376722563fbf837b175085"]},"justifications":null}}
11:11:05 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
                                 rpcMethod: state_getStorageAt
                                 rpcParams: ["0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7","0x6e7d988e2b0f4cdafd996913113d63ce3dc371a130ec4ed7d019b61ab64d44c3"]
11:11:05 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0x6e7d988e2b0f4cdafd996913113d63ce3dc371a130ec4ed7d019b61ab64d44c3"]
11:11:05 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
11:11:05 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
11:11:05 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 8
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0x6e7d988e2b0f4cdafd996913113d63ce3dc371a130ec4ed7d019b61ab64d44c3"]
                                 rpcResponse: {"id":8,"jsonrpc":"2.0","result":{"specName":"kusama","implName":"parity-kusama","authoringVersion":2,"specVersion":1001003,"implVersion":0,"apis":[["0xdf6acb689907609b",4],["0x37e397fc7c91f5e4",2],["0x40fe3ad401f8959a",6],["0xd2bc9897eed08f15",3],["0xf78b278be53f454c",2],["0xaf2c0297a23e6d3d",7],["0x49eaaf1b548a0cb0",3],["0x91d5df18b0d2cf58",2],["0x2a5e924655399e60",1],["0xed99c5acb25eedf5",3],["0xcbca25e39f142387",2],["0x687ad44ad37f03c2",1],["0xab3c0572291feb8b",1],["0xbc9d89904f5b923f",1],["0x37c8bb1350a9a2a8",4],["0xf3ff14d5ab527059",3],["0x17a6bc0d0062aeb3",1],["0x18ef58a3b67ba770",1],["0xfbc577b9d747efd6",1]],"transactionVersion":25,"stateVersion":1}}
11:11:05 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 7
                                 rpcMethod: state_getStorageAt
                                 rpcParams: ["0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7","0x6e7d988e2b0f4cdafd996913113d63ce3dc371a130ec4ed7d019b61ab64d44c3"]
                                 rpcResponse: {"id":7,"jsonrpc":"2.0","result":"0xa40000000000000042b12043551702000000010000003501e8030000beaea1 [redacted]  91189cae6f647464742c89258bfa746c5e2f61885d07197ccf2b60fee49762d7a68726000000500000000000010000000000076a6922fecd7ef50100020000"}
11:11:05 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 9
                                 rpcMethod: chain_getHeader
                                 rpcParams: ["0xd44ca70138cb429b522eb8ef8cdd5df613e58402e664466bb1c1573fc92ccdfe"]
11:11:05 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 9
11:11:07 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 9
                                 rpcMethod: chain_getHeader
                                 rpcParams: ["0xd44ca70138cb429b522eb8ef8cdd5df613e58402e664466bb1c1573fc92ccdfe"]
                                 rpcResponse: {"id":9,"jsonrpc":"2.0","result":{"parentHash":"0xbeaea1e3cc2cabe4db6c4f4c109997166bb6a43aa554741658970b39406ef5aa","number":"0x015876c9","stateRoot":"0xd9cf52eaa7d6218a1d3779e3ed466c187da241bccce02de555688266521c2efb","extrinsicsRoot":"0xda173d37779e431f6df722b5dc29a533bafd2db7702c83ea78ea3a2d6179c4a5","digest":{"logs":["0x0642414245b501030d000000852f0211000000005ab998d14650d5cd9a76f53c3bcf2b06e7aeb0b2d37376e8bdab80cd6b4f53648e5bc7f0d15adcd031d64fa4f715ec450ffaaac378f31fbcfa4379edaf17ae0d44e3b4487023c36d084e7286e0bbe9e49ad650feccdef09ff7f34231f34d0a09","0x044245454684034291c27a7bd5c755d211e232f1172d3013fd2be3b88f5d7c3723431c2780da86","0x0542414245010108a14482d488c4a8969778abf9e8a17c2bd9338de9a3978bd08d153af5e4a3527254e2e92054b0ca785ec70868a43ba2b5bbb520cf376722563fbf837b175085"]}}}
11:11:07 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 10
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0xbeaea1e3cc2cabe4db6c4f4c109997166bb6a43aa554741658970b39406ef5aa"]
11:11:07 DEBUG sqd:processor:rpc rpc call
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 11
                                 rpcMethod: state_getMetadata
                                 rpcParams: ["0xbeaea1e3cc2cabe4db6c4f4c109997166bb6a43aa554741658970b39406ef5aa"]
11:11:07 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 10
11:11:07 DEBUG sqd:processor:rpc rpc send
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 11
11:11:09 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 10
                                 rpcMethod: state_getRuntimeVersion
                                 rpcParams: ["0xbeaea1e3cc2cabe4db6c4f4c109997166bb6a43aa554741658970b39406ef5aa"]
                                 rpcResponse: {"id":10,"jsonrpc":"2.0","result":{"specName":"kusama","implName":"parity-kusama","authoringVersion":2,"specVersion":1001003,"implVersion":0,"apis":[["0xdf6acb689907609b",4],["0x37e397fc7c91f5e4",2],["0x40fe3ad401f8959a",6],["0xd2bc9897eed08f15",3],["0xf78b278be53f454c",2],["0xaf2c0297a23e6d3d",7],["0x49eaaf1b548a0cb0",3],["0x91d5df18b0d2cf58",2],["0x2a5e924655399e60",1],["0xed99c5acb25eedf5",3],["0xcbca25e39f142387",2],["0x687ad44ad37f03c2",1],["0xab3c0572291feb8b",1],["0xbc9d89904f5b923f",1],["0x37c8bb1350a9a2a8",4],["0xf3ff14d5ab527059",3],["0x17a6bc0d0062aeb3",1],["0x18ef58a3b67ba770",1],["0xfbc577b9d747efd6",1]],"transactionVersion":25,"stateVersion":1}}
11:11:09 DEBUG sqd:processor:rpc rpc response
                                 rpcUrl: ws://localhost:8000
                                 rpcId: 11
                                 rpcMethod: state_getMetadata
                                 rpcParams: ["0xbeaea1e3cc2cabe4db6c4f4c109997166bb6a43aa554741658970b39406ef5aa"]
                                 rpcResponse: {"id":11,"jsonrpc":"2.0","result":"0x6d6574610e350e000c1c73705f636f72651863727970746f2c41636 [redacted] 374696f6e5061796d656e742d0e8d01310e"}
11:11:10 INFO  sqd:processor 22574794 / 22574794, rate: 893 blocks/sec, mapping: 50 blocks/sec, 50 items/sec, eta: 0s
```

as you can see from the last line, the indexer says it has indexed the latest kusama block `22574794` however, chopsticks shows nothing, and the head is supposed to be at `22568290` which is what I started chopsticks with.
```
yarn start --runtime-log-level 5 --config ./kusama.yml
[11:11:00.108] INFO: Kusama RPC listening on port 8000
    app: "chopsticks"
```

This is confirmed if I push a tx, it creates a block as expected.
```
INFO (block-builder): Kusama building #22,568,291
    app: "chopsticks"
    number: 22568291
    extrinsics: [
      "0x91038400fa8e003cb5d22db1e8658e05…34d00c4f001e04000000000000000000"
    ]
    umpCount: 0
```

However, it must have told the indexer that the head is elsewhere, at 22574794.

**Comment by ermalkaleci** [comment]
run with tracing enabled to see what's been requested and returned

**Comment by Tbaut** [comment]
it's just with `RUST_LOG=trace` right?

```bash
RUST_LOG=trace yarn start --runtime-log-level 5 --config ./kusama.yml

Calling Metadata_metadata
Completed Metadata_metadata
[11:45:11.813] INFO: Kusama RPC listening on port 8000
    app: "chopsticks"
Calling Metadata_metadata
Completed Metadata_metadata
Calling Metadata_metadata
Completed Metadata_metadata
Calling Metadata_metadata
Completed Metadata_metadata
Calling Metadata_metadata
Completed Metadata_metadata

```

**Comment by ermalkaleci** [comment]
LOG_LEVEL=trace

**Comment by ermalkaleci** [comment]
I think the issue may be here `    }
[11:53:49.237] TRACE (ws): Received single request
    app: "chopsticks"
    req: {
      "id": 14,
      "jsonrpc": "2.0",
      "method": "chain_getBlockHash",
      "params": [
        "0x1585d62"
      ]
    }`

getBlockHash requires number but hexstring is passed instead

**Comment by Tbaut** [comment]
Any chance you can handle this still as a hex string? It's been working for a regular node without issue.

**Comment by ermalkaleci** [comment]
> Any chance you can handle this still as a hex string? It's been working for a regular node without issue.

#722

**Comment by Tbaut** [comment]
Thanks, it's not it unfortunately. Let me open a new issue dedicated to it.

**Review by Tbaut — APPROVED** [review]
solving the issue I opened. Thanks

**Pull request merged**
