### PR TITLE
no auto block in manual mode

### PR DESCRIPTION
**Pull request by xlc**
when block building mode is manual, it should be manual

### CODE REVIEW

**Comment by xlc** [comment]
@ermalkaleci Moonbeam and Astar is currently always having messageQueue.bookStateFor(Parent) so unconditionally builds extra block when received messages and that breaks e2e tests. Not sure why that is happening but this will be an easy fix to get the e2e tests working with some tweaks

**Comment by ermalkaleci** [comment]
@xlc I disabled it auto processing https://github.com/AstarNetwork/e2e-tests/pull/70/files#diff-aa74785dd9e1c615d463ffed54f55bb20f72f4e5dadccc2d7b61a250b0907b29R19-R21
I will take a look today

**Comment by ermalkaleci** [comment]
We have this for Parent, I don't know if it's a bug or not. Chopsticks will check the size which is gt 0 and build although we handle queued messages on idle
```
[
      Parent
]
{
      begin: 57
      end: 57
      count: 1
      readyNeighbours: null
      messageCount: 1
      size_: 11
 }
 ```

**Comment by ermalkaleci** [comment]
@xlc I think rather than disabled it on manual mode ( I think it should cause other problems), we instead check `end > begin`. I will solve current issue

**Comment by xlc** [comment]
> @xlc I think rather than disabled it on manual mode ( I think it should cause other problems), we instead check `end > begin`. I will solve current issue

that will be better. you want to make a PR?

**Comment by ermalkaleci** [comment]
@xlc you can just update this one

**Review by ermalkaleci — APPROVED** [review]

**Pull request merged**
