### PR TITLE
fix deps and update version

### LINKED ISSUE #770: latest release 0.12.0 is broken
chopsticks package doesn't have @polkadot/api dependency 
Screenshot 2024-06-03 at 10 58 28 AM

` code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/utils/fetch-storages.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/context.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/setup-with-server.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/index.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/dist/cjs/cli.js',
    '/Users/ermal/.npm/_npx/c1c4d257924715f9/node_modules/@acala-network/chopsticks/chopsticks.cjs'
  ]`

### PR DESCRIPTION
**Pull request by qiweiii**
fix #770

### CODE REVIEW

**Comment by xlc** [comment]
any checks we can do on CI to detect this issue before release?

**Comment by ermalkaleci** [comment]
release beta first

**Comment by qiweiii** [comment]
maybe with this eslint rule: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md

**Comment by qiweiii** [comment]
let's try add a ci check in another pr

**Pull request merged**
