### PR TITLE
refactor decode proof to extract all keys

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Comment by ermalkaleci** [comment]
this will make it easy to implement new inherent #561
decode_proof will find all possible keys so there's no need to inject unchanged ones

**Comment by girazoki** [comment]
thank you!

**Comment by girazoki** [comment]
@ermalkaleci as I am understanding it, now every key that was proven from the previous code and that is not modified will stay be included and proved on the new built block?

**Comment by ermalkaleci** [comment]
yes, you don't need to touch `SetValidationData` inherent. SetValidationData will be executed first and set new proofs which you can read on your inherent from `query.parachainSystem.relayStateProof()`

**Comment by girazoki** [comment]
ah that's amazing. I think it does cover most of our needs so we might propose a PR adding tanssi support. The only thing I am thinking is: what happens if there are some keys being proved in one inherent (set-validation-data) and others in another inherent (authorities-noting in our case) in production? Probably the nibbles passed to set-validation-data do not include all keys to be able to fork correctly.

We might propose the possibility to add additional keys to set-validation-data inherent if that's fine in the PR that supports tanssi (in other words, being able to add additional keys to the `WellKnownKeys` struct)

**Comment by girazoki** [comment]
the other thing we can do is refactor our node to inject a single proof (in set-validation-data) that contains all keys we need to prove. That should work with this implementation and I think its cleaner!

**Comment by ermalkaleci** [comment]
I think I was wrong. I will look again tomorrow, maybe it needs a refactor

**Pull request merged**
