### PR TITLE
storage null value not handled properly

### PR DESCRIPTION
**Pull request by qiweiii**
fixes: #515

### CODE REVIEW

**Review by xlc — APPROVED** [review]

**Comment by ermalkaleci** [comment]
This is very tricky

**Comment by qiweiii** [comment]
the storage-migrate test is not passed because before this pr, null value storage is marked as Deleted, so the storage-migrate test works, but now it allows null value...  so maybe there is some info that can help us distinguish different kinds of null values?

**Comment by ermalkaleci** [comment]
leave this to me

**Comment by ermalkaleci** [comment]
I think it should work. but let me confirm

**Comment by ermalkaleci** [comment]
yes it works fine. Just value needs to be '0x'

**Comment by ermalkaleci** [comment]
no change is needed

**Pull request closed without merging**
